version: '2'
services:
  nginx:
    build: ./nginx/
    ports:
      - 80:80
    links:
      - phpfpm
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    volumes_from:
      - project

  phpfpm:
    image: oupula/php-5.6
    platform: linux/amd64
    ports:
      - 9000:9000
    links:
      - mysql
    volumes:
      - ./php/phpfpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./logs/php:/var/log/php
    volumes_from:
      - project

  project:
    image: alpine:latest
    volumes:
      - ../htdocs:/var/www/htdocs
    command: "true"

  mysql:
    image: mariadb:10.5.8
    container_name: project-db
    ports:
      - 3306:3306
    volumes:
      - ./databases:/var/lib/mysql
    env_file:
      - .env.db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    restart: always
    ports:
      - 8084:80
    links:
      - phpfpm
      - mysql
    env_file:
      - .env.phpmyadmin
